### ISSUE TITLE
Fatal exception: Negative branch length

### ISSUE THREAD

**Issue by FredericBlum** [NicoNeureiter/contactrees#3]
I am currently trying to reproduce the example and to apply the procedure to my own data. In both cases however, both when running `bantu-contactrees.xml` and with the xml of my own data, I receive the following error message:

```
         Sample ESS(posterior)          prior     likelihood      posterior
              0              N       -25.9378   -198254.1509   -198280.0887 --
java.lang.RuntimeException: Negative branch length: -1.389820202614457
	at beast.evolution.likelihood.BeagleTreeLikelihood.traverse(Unknown Source)
	at beast.evolution.likelihood.BeagleTreeLikelihood.calculateLogP(Unknown Source)
	at beast.evolution.likelihood.TreeLikelihood.calculateLogP(Unknown Source)
	at beast.core.util.CompoundDistribution.calculateLogP(Unknown Source)
	at beast.core.util.CompoundDistribution.calculateLogP(Unknown Source)
	at beast.core.MCMC.propagateState(Unknown Source)
	at beast.core.MCMC.doLoop(Unknown Source)
	at beast.core.MCMC.run(Unknown Source)
	at beast.app.BeastMCMC.run(Unknown Source)
	at beast.app.beastapp.BeastMain.<init>(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)Fatal exception: Negative branch length: -1.389820202614457

	at beast.app.beastapp.BeastLauncher.run(Unknown Source)
	at beast.app.beastapp.BeastLauncher.main(Unknown Source)
Fatal exception: Negative branch length: -1.389820202614457

BEAST has terminated with an error. Please select QUIT from the menu.
```

This is with Beast version v.2.6.7

**Comment by FredericBlum** [comment]
This only happens when running `bantu-contactrees.xml`, not with `bantu-beastling.xml`. Do you have an idea what could cause this problem?

**Comment by NicoNeureiter** [comment]
This was due to the wrong tree-operators in the bantu-contactrees.xml. I replaced the tree operators by contacTrees pendants which ensure that contact edges remain valid (8a10f019154508378ff0f9149a08280294305891) and added the explanation in the walkthrough (8bdaa7db8b5f0b5083688cb5ad2928fa3860aa51).
